# Generated by Django 3.1.7 on 2021-06-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210620_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='media/avatar.png', upload_to='blog_pics/%Y/%m/%d/'),
        ),
    ]
